{
    "name": "Quality Control",
    "version": "13.0.2.2.0",
    "category": "Quality Control",
    "license": "AGPL-3",
    "summary": "Generic infrastructure for quality tests.",
    "author": "Tria Trading Plc",
    "website": "",
    "depends": ["product","stock"],
    "data": [
        "data/quality_control_data.xml",
        "security/quality_control_security.xml",
        "security/ir.model.access.csv",
        "wizard/qc_test_wizard_view.xml",
        "views/qc_menus.xml",
        "views/qc_inspection_view.xml",
        "views/qc_test_category_view.xml",
        "views/qc_test_view.xml",
        "views/qc_trigger_view.xml",
        "views/product_template_view.xml",
        "views/product_category_view.xml",
    ],
    "demo": ["demo/quality_control_demo.xml"],
    "installable": True,
}
