{
  'name':'Member Custom',
  'version': '1.1',
  'description': 'This will customize odoo',
  'author': 'Samra Solomon',
  'depends': [
    'membership',
    'board',
    'mail',
    'reconciliation',
    'hr_employee_medical_examination',
    'utm',
    'web_notify',
    'stock',
    'base_user_role',
    'report'
  ],
  'data': [
    'security/security.xml',
    'security/ir.model.access.csv',
    'data/res_edlevel.xml',
    'data/field_study.xml',
    'data/ethnic_groups.xml',
    'data/payment_fee_configuration.xml',
    'data/inter_personal_skills.xml',
    'data/one_city.xml',
    'data/training_centers.xml',
    'data/member_leader_responsibility.xml',
    'data/members_organization.xml',
    'data/auto_remainder.xml',
    'data/activity_type.xml',
    'wizard/archive.xml',
    # 'views/complaint_template_views.xml',
    'views/payment_sequence.xml',
    'views/attachment_field_modification_views.xml',
    'views/assets.xml',
    'views/member_fields_modification_views.xml',
    'views/minor_configurations.xml',
    'views/membership_payment.xml',
    'views/dashboard.xml',
    'views/membership_handlers_views.xml',
    'views/member_cells_offices.xml',
    'views/candidate_views.xml',
    'views/supporter_views.xml',
    'views/registration.xml',
    'views/donors.xml',
    'views/training.xml',
    'views/complaint_form_views.xml',
    'views/transfer.xml',
    'views/assembly.xml',
    'views/report.xml',
    'report/member_report_views.xml',
    'report/member_report_templates.xml',
    'report/member_report.xml',
    'report/member_detail_template.xml',
    'report/member_tempo_id.xml',
    'report/complaint_report_views.xml',
    'report/complaint_report_templates.xml',
    'report/membership_payment_report.xml',
    'report/training_certificate.xml',
    'report/participation_certificate.xml',
    'report/mail_template_for_complaint.xml',
    'report/mail_template_for_member_notification.xml',
    'report/mail_template_for_transfer.xml',
    'data/inter_personal_skills.xml',
  ],
  'category': 'Member/Handlers',
  'application': True,
  'installable': True,
  'auto_install': False,
  'sequence': 1
}
