{
  'name':'Member Custom Registration',
  'version': '1.1',
  'description': 'This will customize odoo',
  'author': 'Tria Trading',
  'depends': [
    'utm',
    'members_features',
  ],
  'data': [
    'security/ir.model.access.csv',
    'data/auto_remainder.xml',
    'data/activity_type.xml',
    'wizard/archive.xml',
    'views/payment_sequence.xml',
    'views/assets_data.xml',
    'views/member_fields_modification_views.xml',
    'views/candidate_views.xml',
    'views/supporter_views.xml',
    'views/registration.xml',
    'views/donors.xml',
    'views/importation_module.xml',
    'views/dashboard.xml',
    'report/member_report_views.xml',
    'report/member_report_templates.xml',
    'report/member_detail_template.xml',
    'report/member_tempo_id.xml',
    'report/mail_template_for_member_notification.xml',
    'report/mail_template_for_email_passport.xml',
  ],
  # 'category': 'Member/Handlers',
  'application': True,
  'installable': True,
  'auto_install': False,
  'sequence': 1
}
