{
  'name':'Member Custom Minor Configuration',
  'version': '1.1',
  'description': 'This will customize odoo',
  'author': 'Tria Trading',
  'depends': [
    'board',
    'mail',
    'reconciliation',
    'contacts',
    'utm',
    'base_user_role',
    'web_notify',
  ],
  'data': [
    'security/security.xml',
    'security/ir.model.access.csv',
    'data/res_edlevel.xml',
    'data/field_study.xml',
    'data/ethnic_groups.xml',
    'data/payment_fee_configuration.xml',
    'data/inter_personal_skills.xml',
    'data/member_leader_responsibility.xml',
    'data/members_organization.xml',
    'data/training_types.xml',
    'data/fed_states_ethiopia.xml',
    'views/member_fields_modification_views.xml',
    'views/minor_configurations.xml',
    'views/fed_states_ethiopia_view.xml',
    'views/membership_payment.xml',
    'views/training.xml',
  ],
  'category': 'Member/Handlers',
  'application': True,
  'installable': True,
  'auto_install': False,
  'sequence': 1
}
