# -*- coding: utf-8 -*-
{
    'name': 'Open HRMS Gratuity Settlement',
    'version': '13.0.2.0.0',
    'summary': """Employee Gratuity Settlement""",
    'author': 'Cybrosys Techno solutions,Open HRMS',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'category': 'Generic Modules/Human Resources',
    'website': "https://www.openhrms.com",
    'depends': ['base', 'hr', 'hr_payroll_community', 'hr_payroll_account_community', 'account', 'budget', 'hr_expense'],
    # 'depends': ['base', 'hr', 'hr_payroll_community', 'hr_payroll_account_community', 'account', 'hr_expense'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/gratuity_configuration.xml',
        'data/gratuity_product.xml',
        'wizard/archive.xml',
        'views/hr_gratuity_view.xml',
        'views/hr_gratuity_accounting_configuration.xml',
        'views/gratuity_configuration_view.xml',
        'views/gratuity_sequence.xml',
        'views/hr_contract_views.xml',
        # 'views/hr_training_view.xml',
        'views/hr_expense_view.xml',
        # 'views/hr_gratuity_view_custom.xml',
        'security/ir.model.access.csv',
    ],
    'images': ['static/description/banner.png'],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
