{
  'name':'Member Custom Special Features',
  'version': '1.1',
  'description': 'This will customize odoo',
  'author': 'Tria Trading',
  'depends': [
    'utm',
    'members_handlers_annual_plans',
    'hr_employee_medical_examination',
    'stock',
    'report',
  ],
  'data': [
    'security/ir.model.access.csv',
    'data/auto_remainder.xml',
    'data/activity_type.xml',
    'views/assets.xml',
    'views/training.xml',
    'views/complaint_form_views.xml',
    'views/payment_sequence.xml',
    'views/transfer.xml',
    'views/assembly.xml',
    'views/membership_payment.xml',
    'views/cell_meeting_inherit.xml',
    'views/report.xml',
    'report/member_report_views.xml',
    'report/complaint_report_views.xml',
    'report/complaint_report_templates.xml',
    'report/training_certificate.xml',
    'report/participation_certificate.xml',
    'report/mail_template_for_complaint.xml',
    'report/mail_template_for_transfer.xml',
    'report/membership_payment_report.xml',
  ],
  # 'category': 'Member/Handlers',
  'application': True,
  'installable': True,
  'auto_install': False,
  'sequence': 1
}
